# Site settings
title: "Narendra Singh Shekhawat"
description: "It's not only my resume, it's me."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Narendra Singh Shekhawat"
resume_title:                   "Data Manager | ODK Programmer | m-Health Enthusiast"
resume_contact_email:           "narendraa.singhshekhawat@gmail.com"
resume_contact_telephone:       "+91-7737777476"
#resume_contact_address:         "IIHMR, Jaipur"
resume_header_contact_info: "+91-7737777476 | narendraa.singhshekhawat@gmail.com"
resume_header_intro: "<p>Aim to use and learn technology for noble purposes to advance human rights. I am interested in any work which challenges me especially on technology front. Bringing technological solutions to complex real-world problems excite me and give me a sense of fulfilment.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/iamnarendrasingh"
  #resume_twitter_url:           "https://twitter.com/nnnwithnnn"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/narendraa-singh/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
